'use client';
import Link from 'next/link';
import { ArrowRight, Check, CheckCircle2, Heart, Leaf, Route, Sparkles, Sun, Droplets, Footprints, Moon, Salad, Users } from 'lucide-react';

const today=[
 {icon:Droplets,title:'ดื่มน้ำ',sub:'เป้าหมาย 2.5 ลิตร',tone:'bg-[#eef9f1] text-[#26956f]'},
 {icon:Footprints,title:'เดิน',sub:'เป้าหมาย 6,000 ก้าว',tone:'bg-[#fff3ed] text-[#e47a45]'},
 {icon:Salad,title:'ผัก',sub:'อย่างน้อย 2 มื้อ',tone:'bg-[#f0f8e8] text-[#5d9a49]'},
 {icon:Moon,title:'การนอน',sub:'7–8 ชั่วโมง',tone:'bg-[#eef4fb] text-[#6b8fbe]'},
];
const quick=[
 {icon:Heart,title:'เข้าใจสุขภาพตัวเองง่ายขึ้น',text:'รู้ว่าควรเริ่มจากตรงไหน'},
 {icon:Leaf,title:'ทำสิ่งเล็ก ๆ ได้ทุกวัน',text:'ไม่ต้องสมบูรณ์แบบก็เริ่มได้'},
 {icon:Users,title:'มีเพื่อนร่วมทาง',text:'วันที่ไม่ไหวก็ยังมีคนช่วยคิด'},
 {icon:Sparkles,title:'ค่อย ๆ แข็งแรงขึ้น',text:'เพื่อใช้ชีวิตกับคนที่รักได้นานขึ้น'},
];
export default function Home(){return <main className="bg-[#fbf8ef] text-[#294438]">
<section className="mx-auto max-w-[1500px] px-4 pt-5 md:px-7 md:pt-7"><div className="overflow-hidden rounded-[34px] bg-white shadow-[0_18px_60px_rgba(64,78,55,.10)] ring-1 ring-[#eee5d4]"><div className="grid lg:grid-cols-[.9fr_1.25fr]">
<div className="relative flex flex-col justify-center px-7 py-10 md:px-12 md:py-12 lg:py-14"><div className="mb-4 inline-flex w-fit items-center gap-2 rounded-full bg-[#f1f6e8] px-4 py-2 text-[13px] font-medium text-[#42704e]"><Leaf size={15}/> Your Health Journey</div><h1 className="max-w-[570px] text-[2.15rem] font-semibold leading-[1.22] tracking-[-.035em] text-[#3f443f] md:text-[3.15rem]">สุขภาพดีวันนี้<br/><span className="text-[#28744e]">เพื่ออยู่กับคนที่คุณรัก</span><br/><span className="font-serif font-medium italic text-[#c89635]">ไปนาน ๆ</span> <span className="text-[#c89635]">♡</span></h1><p className="mt-5 max-w-[540px] text-[16px] leading-8 text-[#69756e]">เริ่มจากเข้าใจสุขภาพของตัวเองง่าย ๆ แล้วค่อย ๆ ทำสิ่งเล็ก ๆ ที่เหมาะกับชีวิตเรา มีเพื่อนช่วยคิดและเดินไปด้วยกันทุกวัน</p><div className="mt-6 flex flex-wrap items-center gap-3"><Link href="/assessment" className="group inline-flex items-center gap-3 rounded-full bg-[#087b58] px-6 py-3.5 text-[15px] font-semibold text-white shadow-lg shadow-[#087b58]/15 transition hover:-translate-y-0.5">เริ่มประเมินสุขภาพฟรี <span className="flex h-7 w-7 items-center justify-center rounded-full bg-white/15 group-hover:translate-x-1 transition"><ArrowRight size={17}/></span></Link><span className="text-[12px] text-[#89928b]">ใช้เวลาประมาณ 3–5 นาที</span></div></div>
<div className="relative min-h-[420px] overflow-hidden lg:min-h-[590px]"><img src="https://hhs.iowa.gov/sites/default/files/styles/hero_1440px_x_604px/public/images/2024-11/Website%20Homepage%20Feature%20Image.png.webp?itok=NvUNEyUk" alt="ครอบครัวหลายวัยใช้เวลาร่วมกันอย่างมีความสุข" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#fffaf0]/25 via-transparent to-[#2b5d43]/5"/><div className="absolute bottom-5 left-5 right-5 rounded-[24px] bg-white/90 p-4 shadow-lg backdrop-blur-sm ring-1 ring-white"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#f4eedc] text-[#c89635]"><Heart size={20} className="fill-[#f1dfac]"/></div><div><p className="text-[13px] text-[#7b857e]">สุขภาพดี ไม่ใช่แค่เพื่อตัวเรา</p><p className="text-[17px] font-semibold text-[#236746]">แต่เพื่อคนที่เรารัก ❤️</p></div></div></div></div></div></div></section>

<section className="mx-auto max-w-[1500px] px-4 py-6 md:px-7"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{quick.map(({icon:Icon,title,text})=><div key={title} className="rounded-[24px] bg-white/80 p-5 ring-1 ring-[#eee5d4]"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#f2f7e9] text-[#5c9852]"><Icon size={19}/></div><div className="mt-3 text-[15px] font-semibold text-[#405348]">{title}</div><div className="mt-1 text-[13px] leading-6 text-[#8a938c]">{text}</div></div>)}</div></section>

<section className="mx-auto max-w-[1500px] px-4 pb-5 md:px-7"><div className="grid gap-5 lg:grid-cols-[1.05fr_1.35fr]">
<div className="rounded-[30px] bg-white p-6 shadow-[0_12px_45px_rgba(55,75,58,.06)] ring-1 ring-[#eee5d4]"><div className="flex items-center justify-between"><div><div className="text-[13px] text-[#8a948c]">วันนี้ของคุณ</div><h2 className="mt-1 text-[24px] font-semibold text-[#176646]">วันนี้เริ่มต้นดูแลสุขภาพง่าย ๆ ด้วยกันนะคะ 🌿</h2></div><span className="rounded-full bg-[#f1f6e8] px-3 py-1 text-[12px] text-[#66825b]">ง่าย ๆ 4 เรื่อง</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{today.map(({icon:Icon,title,sub,tone})=><div key={title} className="rounded-[22px] border border-[#eee9dd] bg-[#fffdfa] p-4"><div className="flex items-center gap-3"><div className={`flex h-10 w-10 items-center justify-center rounded-2xl ${tone}`}><Icon size={19}/></div><div><div className="font-semibold text-[#45544b]">{title}</div><div className="text-[12px] text-[#929a94]">{sub}</div></div></div><div className="mt-3 flex items-center justify-between text-[12px] text-[#8a938c]"><span>ค่อย ๆ ทำได้ค่ะ</span><button className="flex h-8 w-8 items-center justify-center rounded-full border border-[#cfe8d9] text-[#15906c] hover:bg-[#eff9f2]"><Check size={16}/></button></div></div>)}</div><div className="mt-4 rounded-[20px] bg-[#f8f4e8] px-4 py-3 text-[13px] text-[#69746d]"><span className="font-semibold text-[#236746]">เลือกทำแค่ 1 อย่างก่อนก็ได้ค่ะ ❤️</span> ความสม่ำเสมอสำคัญกว่าความสมบูรณ์แบบ</div></div>
<div className="rounded-[30px] bg-[#f3f7ec] p-6 ring-1 ring-[#e4ead7]"><div className="flex items-center justify-between"><div><div className="text-[13px] text-[#718078]">My Health Journey</div><h2 className="mt-1 text-[24px] font-semibold text-[#176646]">ทุกก้าวเล็ก ๆ มีความหมาย</h2></div><Route className="text-[#78a45c]"/></div><div className="mt-7 flex items-center px-2"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-white ring-4 ring-[#deebd0] text-[#6f9e55]"><Leaf size={20}/></div><div className="h-1 flex-1 bg-[#b9d49c]"/><div className="flex h-9 w-9 items-center justify-center rounded-full bg-white text-[#df9d9d]"><Heart size={17}/></div><div className="h-1 flex-1 bg-[#d8dfd0]"/><div className="flex h-9 w-9 items-center justify-center rounded-full bg-white text-[#b6b9ae]"><Sun size={17}/></div><div className="h-1 flex-1 bg-[#e3e6df]"/><div className="flex h-9 w-9 items-center justify-center rounded-full bg-white text-[#c8c5b5]"><Sparkles size={17}/></div></div><div className="mt-3 grid grid-cols-4 text-center text-[12px] font-medium text-[#7b887f]"><span>เริ่มต้น</span><span>ดูแลต่อเนื่อง</span><span>แข็งแรงขึ้น</span><span>ใช้ชีวิตเต็มที่</span></div><div className="mt-6 flex items-center gap-3 rounded-[22px] bg-white/80 p-4"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#edf5df] text-[#6d9954]"><CheckCircle2 size={21}/></div><div><div className="font-semibold text-[#496050]">คุณเริ่มต้นแล้วค่ะ 🌱</div><div className="mt-1 text-[13px] leading-6 text-[#7e8981]">วันนี้ไม่ต้องทำทุกอย่าง แค่เลือกหนึ่งก้าวที่ทำได้จริง</div></div></div><Link href="/journey" className="mt-4 inline-flex items-center gap-2 text-[13px] font-semibold text-[#35764e]">ดูเส้นทางของฉัน <ArrowRight size={15}/></Link></div></div></section>

<section className="mx-auto max-w-[1500px] px-4 pb-12 md:px-7"><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-[30px] bg-white p-6 ring-1 ring-[#eee5d4]"><div className="flex items-center justify-between"><div><div className="text-[13px] text-[#8a948c]">คะแนนสุขภาพของคุณ</div><h2 className="mt-1 text-[22px] font-semibold text-[#176646]">เริ่มต้นจากตัวเรา ไม่ต้องเปรียบเทียบกับใคร</h2></div><div className="flex h-16 w-16 items-center justify-center rounded-full border-[7px] border-[#e5efd5] border-t-[#6d9b55] text-[20px] font-semibold text-[#3f7651]">68</div></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{['โภชนาการ 72','การเคลื่อนไหว 55','การนอน 60','ความเครียด 75'].map(x=><div key={x} className="rounded-2xl bg-[#fbfaf4] p-3 text-[12px] text-[#718078]">{x}</div>)}</div><Link href="/result" className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#f1f6e8] px-4 py-2.5 text-[13px] font-semibold text-[#3d744d]">ดูเส้นทางสุขภาพของฉัน <ArrowRight size={15}/></Link></div><div className="rounded-[30px] bg-[#fffdf7] p-6 ring-1 ring-[#eee5d4]"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-[#f3e7d4] text-[#c89635]"><Heart size={20}/></div><div><div className="text-[13px] text-[#7d887f]">เพื่อนช่วยคิด</div><h2 className="text-[21px] font-semibold text-[#176646]">คุยกับเราได้ทุกวัน ❤️</h2></div></div><p className="mt-4 text-[14px] leading-7 text-[#68756d]">ไม่รู้จะเริ่มตรงไหนก็ไม่เป็นไรค่ะ เลือกหัวข้อที่ตรงกับคุณ แล้วค่อย ๆ คิดไปด้วยกัน</p><div className="mt-4 flex flex-wrap gap-2"><Link href="/ai-coach" className="rounded-full bg-[#f0f6e9] px-3 py-2 text-[12px] text-[#537a50]">วันนี้ไม่มีแรง</Link><Link href="/ai-coach" className="rounded-full bg-[#f0f6e9] px-3 py-2 text-[12px] text-[#537a50]">นอนไม่ค่อยดี</Link><Link href="/ai-coach" className="rounded-full bg-[#f0f6e9] px-3 py-2 text-[12px] text-[#537a50]">อยากเริ่มดูแลตัวเอง</Link></div><Link href="/ai-coach" className="mt-5 inline-flex items-center gap-2 text-[13px] font-semibold text-[#3d744d]">คุยกับเพื่อนช่วยคิด <ArrowRight size={15}/></Link></div></div></section>
</main>}
